## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = '../Part01/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ../Part01/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [6]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
df=DataFrame(app_train)

In [7]:
df.shape

(307511, 122)

#### 列出所有欄位

In [8]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

#### 截取部分資料

In [15]:
df['NAME_CONTRACT_TYPE']

0              Cash loans
1              Cash loans
2         Revolving loans
3              Cash loans
4              Cash loans
5              Cash loans
6              Cash loans
7              Cash loans
8              Cash loans
9         Revolving loans
10             Cash loans
11             Cash loans
12             Cash loans
13             Cash loans
14             Cash loans
15             Cash loans
16             Cash loans
17        Revolving loans
18        Revolving loans
19             Cash loans
20        Revolving loans
21             Cash loans
22             Cash loans
23             Cash loans
24             Cash loans
25             Cash loans
26             Cash loans
27             Cash loans
28             Cash loans
29        Revolving loans
               ...
307481         Cash loans
307482         Cash loans
307483         Cash loans
307484         Cash loans
307485    Revolving loans
307486         Cash loans
307487         Cash loans
307488         Cash loans
307489         Cash loans
307490         Cash loans
307491         Cash loans
307492         Cash loans
307493         Cash loans
307494         Cash loans
307495         Cash loans
307496    Revolving loans
307497         Cash loans
307498         Cash loans
307499         Cash loans
307500         Cash loans
307501         Cash loans
307502         Cash loans
307503         Cash loans
307504         Cash loans
307505         Cash loans
307506         Cash loans
307507         Cash loans
307508         Cash loans
307509         Cash loans
307510         Cash loans
Name: NAME_CONTRACT_TYPE, Length: 307511, dtype: object

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [16]:
 df.rank()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,1.0,295099.0,139116.5,254978.0,101462.5,200855.5,107686.0,227803.0,119491.0,151706.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
1,2.0,141343.5,139116.5,101224.5,101462.5,47100.0,107686.0,274937.0,288143.0,236262.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
2,3.0,141343.5,292872.0,254978.0,255218.0,200855.5,107686.0,15693.0,13681.5,5213.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
3,4.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,131552.5,92975.0,195846.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,141343.5,139116.5,254978.0,101462.5,200855.5,107686.0,105305.5,153607.5,122879.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
5,6.0,141343.5,139116.5,254978.0,101462.5,200855.5,107686.0,61855.0,144645.5,180904.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,103504.0
6,7.0,141343.5,139116.5,101224.5,255218.0,200855.5,245931.0,188492.0,299597.5,262378.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,232348.5,160302.5
7,8.0,141343.5,139116.5,254978.0,255218.0,200855.5,107686.0,295952.0,297835.0,264960.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
8,9.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,85069.0,260706.5,226938.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
9,10.0,141343.5,292872.0,254978.0,101462.5,200855.5,107686.0,131552.5,118638.0,108837.0,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
10,11.0,141343.5,139116.5,101224.5,101462.5,200855.5,245931.0,85069.0,192929.5,116719.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,107709.0,35901.0
11,12.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,925.0,17570.5,28445.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,160302.5
12,13.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,15693.0,3447.0,2566.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,107709.0,35901.0
13,14.0,141343.5,139116.5,254978.0,255218.0,47100.0,245931.0,250044.5,250260.5,190934.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
14,15.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,217099.0,221420.5,220703.0,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
15,16.0,141343.5,139116.5,254978.0,255218.0,200855.5,107686.0,169777.5,90747.5,107712.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
16,17.0,141343.5,139116.5,254978.0,101462.5,47100.0,107686.0,68411.5,152803.0,165360.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,35901.0
17,18.0,141343.5,292872.0,101224.5,101462.5,200855.5,245931.0,30391.0,74801.0,50277.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
18,19.0,141343.5,292872.0,101224.5,101462.5,200855.5,107686.0,85069.0,20824.0,9291.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
19,20.0,141343.5,139116.5,101224.5,101462.5,200855.5,245931.0,46681.0,166205.0,86856.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,160302.5
20,21.0,141343.5,292872.0,254978.0,255218.0,200855.5,107686.0,131552.5,122486.5,118281.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
21,22.0,141343.5,139116.5,101224.5,255218.0,200855.5,245931.0,227803.0,276708.0,246088.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,229383.5
22,23.0,141343.5,139116.5,101224.5,101462.5,47100.0,245931.0,303155.0,148317.0,218872.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,245766.5
23,24.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,33535.5,53949.5,143702.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,202212.5
24,25.0,141343.5,139116.5,254978.0,255218.0,47100.0,289865.0,131552.5,57798.0,42301.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
25,26.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,46681.0,46163.5,30770.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
26,27.0,295099.0,139116.5,101224.5,101462.5,200855.5,107686.0,85069.0,256012.0,177458.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,256485.5,160302.5
27,28.0,141343.5,139116.5,254978.0,101462.5,200855.5,245931.0,85069.0,100118.0,143292.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
28,29.0,141343.5,139116.5,254978.0,255218.0,200855.5,107686.0,274937.0,225843.5,297600.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,107709.0,103504.0
29,30.0,141343.5,292872.0,254978.0,101462.5,200855.5,107686.0,46681.0,29533.5,16541.0,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,307482.0,295099.0,139116.5,254978.0,101462.5,200855.5,107686.0,250044.5,89474.0,106122.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,202212.5
307482,307483.0,141343.5,139116.5,101224.5,255218.0,200855.5,107686.0,250044.5,149925.0,232536.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
307483,307484.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,61855.0,56309.5,76461.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,245766.5
307484,307485.0,141343.5,139116.5,101224.5,255218.0,47100.0,107686.0,305258.5,169003.0,235495.0,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
307485,307486.0,141343.5,292872.0,101224.5,101462.5,200855.5,245931.0,274937.0,29533.5,16541.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
307486,307487.0,141343.5,139116.5,101224.5,255218.0,200855.5,245931.0,282914.5,108228.0,93077.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,103504.0
307487,307488.0,141343.5,139116.5,254978.0,101462.5,200855.5,107686.0,101961.5,266242.5,210408.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,263692.0
307488,307489.0,141343.5,139116.5,101224.5,101462.5,47100.0,107686.0,169777.5,13681.5,46335.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,256485.5,103504.0
307489,307490.0,295099.0,139116.5,101224.5,101462.5,200855.5,107686.0,250044.5,156868.0,136347.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,160302.5
307490,307491.0,141343.5,139116.5,254978.0,101462.5,200855.5,107686.0,30391.0,13681.5,20132.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
307491,307492.0,141343.5,139116.5,254978.0,255218.0,200855.5,289865.0,46681.0,267956.5,211249.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,260694.0
307492,307493.0,141343.5,139116.5,254978.0,255218.0,200855.5,107686.0,305811.0,300249.5,269835.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
307493,307494.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,131552.5,253501.0,246813.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,232348.5,260694.0
307494,307495.0,141343.5,139116.5,254978.0,255218.0,47100.0,245931.0,274937.0,142441.0,279091.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,261560.5,111117.0,107709.0,103504.0
307495,307496.0,141343.5,139116.5,254978.0,255218.0,47100.0,107686.0,203225.0,229559.5,142260.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
307496,307497.0,141343.5,292872.0,101224.5,101462.5,47100.0,107686.0,295952.0,102951.5,80708.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,160302.5
307497,307498.0,141343.5,139116.5,101224.5,255218.0,200855.5,107686.0,203225.0,78479.0,37489.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,255276.0
307498,307499.0,141343.5,139116.5,254978.0,255218.0,200855.5,107686.0,219389.5,289380.0,290127.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,160302.5
307499,307500.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,30391.0,46163.5,42167.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,232348.5,35901.0
307500,307501.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,269069.0,288597.5,237865.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,107709.0,245766.5
307501,307502.0,141343.5,139116.5,101224.5,101462.5,200855.5,305098.0,30391.0,69773.0,36419.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
307502,307503.0,141343.5,139116.5,101224.5,101462.5,200855.5,245931.0,58966.0,46163.5,28185.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,103504.0
307503,307504.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,85069.0,106327.0,88642.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,238807.0,107709.0,160302.5
307504,307505.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,155882.5,101413.5,72380.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
307505,307506.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,85069.0,46163.5,126872.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,258073.5,107709.0,35901.0
307506,307507.0,141343.5,139116.5,254978.0,101462.5,47100.0,107686.0,169777.5,62675.5,181423.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
307507,307508.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,22597.0,69773.0,37143.5,...,152506.0,153664.5,153678.0,153704.5,NaN,NaN,NaN,NaN,NaN,NaN
307508,307509.0,141343.5,139116.5,101224.5,101462.5,200855.5,107686.0,155882.5,204086.5,198816.5,...,152506.0,153664.5,153678.0,153704.5,265146.5,132252.0,128728.5,238807.0,107709.0,103504.0
307509,307510.0,295099.0,139116.5,101224.5,101462.5,200855.5,107686.0,188492.0,112109.5,107966.0,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,111117.0,107709.0,35901.0
307510,307511.0,141343.5,139116.5,101224.5,101462.5,47100.0,107686.0,169777.5,199492.0,284680.5,...,152506.0,153664.5,153678.0,153704.5,132183.5,132252.0,128728.5,258073.5,107709.0,103504.0